#!/bin/bash
echo "Configuring bash-it"
for comp in bash-it git pip pip3 system; do
bash-it enable completion "$comp"
done
for plg in alias-completion base git virtualenv; do
bash-it enable plugin "$plg"
done
for ali in general git; do
bash-it enable alias "$ali"
done
