#!/bin/bash
if [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]; then
  echo "Installing Vundle"
  git clone "https://github.com/VundleVim/Vundle.vim.git" "$HOME/.vim/bundle/Vundle.vim"
fi

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

if test -n "$BASH_VERSION"; then
  PROFILE_SHELL=bash

  if [ ! -d "$HOME/.bash_it" ]; then
    echo "Installing bash-it"
    git clone --depth=1 "https://github.com/Bash-it/bash-it.git" "$HOME/.bash_it"
    $HOME/.bash_it/install.sh
    #TODO experimental 
    bash-it enable alias git
    bash-it enable alias tmux
  fi
fi

# TODO zsh version
